# This is a basic workflow to automatically build a Svelte app and deploy it to GitHub Pages

name: Deploying Globe Stocker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Build
        uses: actions/checkout@v2
        run: |
          cd client
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: client/dist
          retention-days: 1
          if-no-files-found: error
          compression-level: 6
          overwrite: false
      
  deploy:
    need: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: client/dist